name: Deploy Java App to Tencent Cloud

on:
  push:
    branches: [ "master" ]  # 仅在 master 分支推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub 托管的最新 Ubuntu 环境

    steps:
      # **步骤 1：拉取代码**
      - name: Checkout repository
        uses: actions/checkout@v3

      # **步骤 2：设置 Python 环境**
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # **步骤 3：安装 Python 依赖**
      - name: Install Python dependencies
        run: |
          cd python_back
          pip install -r requirements.txt

      # **步骤 4：设置 JDK 17 环境**
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 使用 Eclipse Temurin JDK

      # **步骤 5：Maven 构建并跳过测试**
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # **步骤 6：SCP 上传 JAR 和 Python 代码**
      - name: Upload JAR and Python Code via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            target/*.jar
            python_back/*
          target: "/home/ubuntu/app/"
          strip_components: 1
          overwrite: true

      # **步骤 7：SSH 连接服务器重启服务**
      - name: Restart Service via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 进入应用目录
            cd /home/ubuntu/app
            
            # 停止旧服务（忽略未运行时的错误）
            sudo systemctl stop app.service || true
            
            # 获取最新 JAR 文件（确保只有一个 JAR）
            JAR_FILE=$(ls -t *.jar | head -n 1)
            if [ -n "$JAR_FILE" ]; then
              sudo mv "$JAR_FILE" app.jar
            fi
            
            # 重启服务
            sudo systemctl start app.service
            
            # 查看服务状态
            sudo systemctl status app.service

      # **步骤 8：通知部署成功**
      - name: Notify Deployment Success
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
                Java 应用已成功部署到腾讯云服务器！
                部署时间：${{ github.event.head_commit.timestamp }}
                提交信息：${{ github.event.head_commit.message }}
                提交者：${{ github.event.head_commit.author.name }}
