name: Deploy Java App to Tencent Cloud

on:
  push:
    branches: [ "master" ]  # 仅在master分支推送时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub托管的最新Ubuntu环境

    steps:
      # 步骤1：拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤2：设置JDK 17环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 推荐使用Eclipse Temurin JDK

      # 步骤3：Maven构建并跳过测试（生产环境建议保留测试）
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 步骤4：通过SCP上传JAR到腾讯云服务器
      - name: Upload JAR via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}      # 服务器公网IP
          username: ubuntu                    # 服务器登录用户
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH私钥（GitHub Secrets存储）
          source: "target/*.jar"              # 本地构建产物路径
          target: "/home/ubuntu/app/"         # 服务器目标路径
          strip_components: 1                 # 去除tar包中的顶层目录（如target）
          overwrite: true                     # 覆盖旧文件

      # 步骤5：SSH连接服务器重启服务
      - name: Restart Service via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 进入应用目录
            cd /home/ubuntu/app
            
            # 停止旧服务（忽略未运行时的错误）
            sudo systemctl stop app.service || true
            
            # 重命名最新JAR文件（确保文件名固定）
            sudo mv *.jar app.jar
            
            # 重启服务
            sudo systemctl start app.service
            
            # 查看服务状态（调试用）
            sudo systemctl status app.service